# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build + Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        cache: 'yarn'
    - run: yarn
    - run: yarn build:release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build
        retention-days: 30

  test:

    runs-on: ubuntu-latest

    needs: [build]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        cache: 'yarn'
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: build
        path: build
    - run: yarn
    - run: yarn test
    - run: yarn test:workspaces
    - run: yarn test:workspaces:testnet
