# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        cache: 'yarn'
    - name: Cache
      uses: actions/cache@v2.1.7
      with:
        path: build
        key: build
    - run: yarn
    - run: yarn build

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        cache: 'yarn'
    - name: Cache
      uses: actions/cache@v2.1.7
      with:
        path: build
        key: build
    - run: yarn test
    - run: yarn test:workspaces
